# Generated by Django 4.2.7 on 2025-11-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="project",
            new_name="projects_pr_created_6b02e3_idx",
            old_name="projects_pr_created_idx",
        ),
        migrations.RenameIndex(
            model_name="project",
            new_name="projects_pr_created_c24ee1_idx",
            old_name="projects_pr_created_idx_2",
        ),
    ]
