# Generated by Django 4.2.7 on 2025-11-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="issue",
            new_name="issues_issu_status_003ba6_idx",
            old_name="issues_issu_status_idx",
        ),
        migrations.RenameIndex(
            model_name="issue",
            new_name="issues_issu_priorit_77f54b_idx",
            old_name="issues_issu_priority_idx",
        ),
        migrations.RenameIndex(
            model_name="issue",
            new_name="issues_issu_project_05d549_idx",
            old_name="issues_issu_project_idx",
        ),
        migrations.RenameIndex(
            model_name="issue",
            new_name="issues_issu_reporte_b00eca_idx",
            old_name="issues_issu_reporter_idx",
        ),
        migrations.RenameIndex(
            model_name="issue",
            new_name="issues_issu_assigne_32a375_idx",
            old_name="issues_issu_assignee_idx",
        ),
    ]
