# Generated by Django 4.2.7 on 2025-11-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="comment",
            new_name="comments_co_issue_i_25b7b6_idx",
            old_name="comments_co_issue_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="comments_co_author__4d2625_idx",
            old_name="comments_co_author_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="comments_co_created_5f6a12_idx",
            old_name="comments_co_created_idx",
        ),
    ]
